/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AhBWdUO1iKr
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { useState } from "react"



export function Uploader({videopublisher}:any) {
  const videopublishers = async (title:string,description:string,video:string,setVideo_id:any) => {  
    const videoid = await videopublisher(title,description,video,setVideo_id)
    setVideo_id(videoid)  
  }
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [video, setVideo] = useState('')
  const [video_id, setVideo_id] = useState('')
  return (
    <main className="flex flex-col items-center justify-center min-h-screen py-12 bg-gray-50 sm:px-6 lg:px-8 dark:bg-gray-900">
      <div className="w-full max-w-md space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900 dark:text-gray-100">
            Upload your video
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600 dark:text-gray-400">
            Please fill in the details and select your video file.
          </p>
        </div>
        <form className="mt-8 space-y-6">
          <div className="rounded-md shadow-sm -space-y-px">
            <div>
              <Label htmlFor="title">Title</Label>
              <Input
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200 border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm dark:bg-gray-800 dark:text-gray-100 dark:border-gray-700 dark:placeholder-gray-400 dark:border-gray-800"
                id="title"
                required
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>
            <div>
              <Label htmlFor="description">Description</Label>
              <Textarea
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200 border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm dark:bg-gray-800 dark:text-gray-100 dark:border-gray-700 dark:placeholder-gray-400 dark:border-gray-800"
                id="description"
                required
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>
            <div className="grid w-full max-w-sm items-center gap-1.5">
              <Label htmlFor="video">Video Url</Label>
              <Input
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200 border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm dark:bg-gray-800 dark:text-gray-100 dark:border-gray-700 dark:placeholder-gray-400 dark:border-gray-800"
                id="video"
                required
                type="text"
                value={video}
                onChange={(e) => setVideo(e.target.value)}
              />
              
            </div>
          </div>
          <div>
            <Button className="w-full" onClick={() => videopublishers(title,description,video,setVideo_id)} type="button">
              Upload
            </Button>
          </div>
        </form>
        
        {video_id && (
          <div className="rounded-md bg-gray-100 dark:bg-gray-800 p-4">
          <h2 className="text-center text-2xl font-extrabold text-gray-900 dark:text-gray-100">
            Video Url
          </h2>
          <p className="text-center text-sm text-gray-600 dark:text-gray-400">
            {"https://web3player.vercel.app/watch?id="+video_id}
          </p>
          </div>
        )}
      </div>
    </main>
  )
}
